models:
  # - initial_demand
  - incremental_demand
  - benefits
  # - assign_demand


taz_file_name: taz.csv
# taz_file_name: example.db
taz_table_name: taz # if using sqlite for taz table
taz_taz_column: taz
taz_node_column: node_id

# should tracing be performed in incremental logit, and for which zones and segment
# trace: False
# trace_ptaz: 1455
# trace_ataz: 1493
# trace_segment: nwk1
