models:
  - initial_demand
  - incremental_demand
  - bike_benefits
  - assign_demand

# taz table settings
use_csv: True
use_sqlite: False

taz_file_name: taz.csv
# taz_table_name:  # if use_sqlite: True
taz_taz_column: taz
taz_node_column: node_id

# should tracing be performed in incremental logit, and for which zones and segment
# trace: False
# trace_ptaz: 1455
# trace_ataz: 1493
# trace_segment: nwk1
